export class ActivisionMwMpResponse {
  all: {
    properties: {
      recordLongestWinStreak: number;
      recordXpInAMatch: number;
      accuracy: number;
      losses: number;
      totalGamesPlayed: number;
      score: number;
      winLossRatio: number;
      totalShots: number;
      bestScoreXp: number;
      gamesPlayed: number;
      bestSquardKills: number;
      bestSguardWave: number;
      bestConfirmed: number;
      deaths: number;
      wins: number;
      bestSquardCrates: number;
      kdRatio: number;
      bestAssists: number;
      bestFieldgoals: number;
      bestScore: number;
      recordDeathsInAMatch: number;
      scorePerGame: number;
      bestSPM: number;
      bestKillChains: number;
      recordKillsInAMatch: number;
      suicides: number;
      wlRatio: number;
      currentWinStreak: number;
      bestMatchBonusXp: number;
      bestMatchXp: number;
      bestSguardWeaponLevel: number;
      bestKD: number;
      kills: number;
      bestKillsAsInfected: number;
      bestReturns: number;
      bestStabs: number;
      bestKillsAsSurvivor: number;
      timePlayedTotal: number;
      bestDestructions: number;
      headshots: number;
      bestRescues: number;
      assists: number;
      ties: number;
      recordKillStreak: number;
      bestPlants: number;
      misses: number;
      bestDamage: number;
      bestSetbacks: number;
      bestTouchdowns: number;
      scorePerMinute: number;
      bestDeaths: number;
      bestMedalXp: number;
      bestDefends: number;
      bestSquardRevives: number;
      bestKills: number;
      bestDefuses: number;
      bestCaptures: number;
      hits: number;
      bestKillStreak: number;
      bestDenied: number;
    }
  };
  mode: {
    gun: Record<string, any> | any;
    dom: Record<string, any> | any;
    war: Record<string, any> | any;
    hq: Record<string, any> | any;
    hc_dom: Record<string, any> | any;
    hc_conf: Record<string, any> | any;
    koth: Record<string, any> | any;
    conf: Record<string, any> | any;
    hc_hq: Record<string, any> | any;
    arena: Record<string, any> | any;
    br_dmz: Record<string, any> | any;
    br: Record<string, any> | any;
    sd: Record<string, any> | any;
    grnd: Record<string, any> | any;
    cyber: Record<string, any> | any;
    hc_war: Record<string, any> | any;
    br_all: Record<string, any> | any;
    hc_sd: Record<string, any> | any;
    arm: Record<string, any> | any;
    hc_cyber: Record<string, any> | any;
    infect: Record<string, any> | any
  };
  map: Record<string, any> | any;
  itemData: {
    weapon_sniper: Record<string, any> | any;
    tacticals: Record<string, any> | any;
    lethals: Record<string, any> | any;
    weapon_lmg: Record<string, any> | any;
    weapon_launcher: Record<string, any> | any;
    weapon_pistol: Record<string, any> | any;
    weapon_assault_rifle: Record<string, any> | any;
    weapon_other: Record<string, any> | any;
    weapon_shotgun: Record<string, any> | any;
    weapon_smg: Record<string, any> | any;
    weapon_marksman: Record<string, any> | any;
    weapon_melee: Record<string, any> | any
  };
  scorestreakData: {
    lethalScorestreakData: Record<string, any> | any;
    supportScorestreakData: Record<string, any> | any
  };
  accoladeData: {
    properties: {
      classChanges: number;
      highestAvgAltitude: number;
      killsFromBehind: number;
      lmgDeaths: number;
      riotShieldDamageAbsorbed: number;
      flashbangHits: number;
      meleeKills: number;
      tagsLargestBank: number;
      shotgunKills: number;
      sniperDeaths: number;
      timeProne: number;
      killstreakWhitePhosphorousKillsAssists: number;
      shortestLife: number;
      deathsFromBehind: number;
      higherRankedKills: number;
      mostAssists: number;
      leastKills: number;
      tagsDenied: number;
      killstreakWheelsonKills: number;
      sniperHeadshots: number;
      killstreakJuggernautKills: number;
      smokesUsed: number;
      avengerKills: number;
      decoyHits: number;
      killstreakCarePackageUsed: number;
      molotovKills: number;
      gasHits: number;
      comebackKills: number;
      lmgHeadshots: number;
      smgDeaths: number;
      carrierKills: number;
      deployableCoverUsed: number;
      thermiteKills: number;
      arKills: number;
      c4Kills: number;
      suicides: number;
      clutch: number;
      survivorKills: number;
      killstreakGunshipKills: number;
      timeSpentAsPassenger: number;
      returns: number;
      smgHeadshots: number;
      launcherDeaths: number;
      oneShotOneKills: number;
      ammoBoxUsed: number;
      spawnSelectSquad: number;
      weaponPickups: number;
      pointBlankKills: number;
      tagsCaptured: number;
      killstreakGroundKills: number;
      distanceTraveledInVehicle: number;
      longestLife: number;
      stunHits: number;
      spawnSelectFlag: number;
      shotgunHeadshots: number;
      bombDefused: number;
      snapshotHits: number;
      noKillsWithDeath: number;
      killstreakAUAVAssists: number;
      killstreakPersonalUAVKills: number;
      tacticalInsertionSpawns: number;
      launcherKills: number;
      spawnSelectVehicle: number;
      mostKillsLeastDeaths: number;
      mostKills: number;
      defends: number;
      timeSpentAsDriver: number;
      bombDetonated: number;
      arHeadshots: number;
      timeOnPoint: number;
      lmgKills: number;
      killstreakUAVAssists: number;
      carepackagesCaptured: number;
      mostKillsLongestStreak: number;
      killstreakCruiseMissileKills: number;
      longestStreak: number;
      destroyedKillstreaks: number;
      hipfireKills: number;
      stimDamageHealed: number;
      skippedKillcams: number;
      leastAssists: number;
      mostMultikills: number;
      highestRankedKills: number;
      killstreakAirstrikeKills: number;
      distanceTravelled: number;
      killstreakKills: number;
      semtexKills: number;
      penetrationKills: number;
      explosionsSurvived: number;
      highestMultikill: number;
      arDeaths: number;
      longshotKills: number;
      proximityMineKills: number;
      tagsMegaBanked: number;
      mostKillsMostHeadshots: number;
      firstInfected: number;
      killstreakCUAVAssists: number;
      throwingKnifeKills: number;
      executionKills: number;
      lastSurvivor: number;
      reconDroneMarks: number;
      deadSilenceKills: number;
      revengeKills: number;
      infectedKills: number;
      killEnemyTeam: number;
      sniperKills: number;
      killstreakCluserStrikeKills: number;
      meleeDeaths: number;
      timeWatchingKillcams: number;
      killstreakTankKills: number;
      noKillNoDeath: number;
      shotgunDeaths: number;
      killstreakChopperGunnerKills: number;
      shotsFired: number;
      stoppingPowerKills: number;
      pistolPeaths: number;
      killstreakShieldTurretKills: number;
      timeCrouched: number;
      noDeathsFromBehind: number;
      bombPlanted: number;
      setbacks: number;
      smgKills: number;
      claymoreKills: number;
      kills10NoDeaths: number;
      pistolHeadshots: number;
      killstreakVTOLJetKills: number;
      headshots: number;
      mostDeaths: number;
      adsKills: number;
      empDroneHits: number;
      defenderKills: number;
      launcherHeadshots: number;
      timesSelectedAsSquadLeader: number;
      killstreakAirKills: number;
      assaults: number;
      fragKills: number;
      killstreakEmergencyAirdropUsed: number;
      captures: number;
      killstreakChopperSupportKills: number;
      spawnSelectBase: number;
      noKill10Deaths: number;
      leastDeaths: number;
      killstreakSentryGunKills: number;
      longestTimeSpentOnWeapon: number;
      lowerRankedKills: number;
      trophySystemHits: number;
      clutchRevives: number;
      lowestAvgAltitude: number;
      pickups: number;
      pistolKills: number;
      reloads: number;
    };
  }
}
